name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true
        default: vX.X.X

jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm install
      - name: Webpack Build Production
        run: npm run prod
      - name: Electron Build Package (Linux)
        run: npm run package -- --linux
      - name: Electron Build Package (macOS)
        run: npm run package -- --macos
      - name: Electron Build Package (Windows)
        run: npm run package -- --windows
      - name: Run Post Release Script
        run: node scripts/post-release.js
      - name: Update Data on Official Site
        run: curl https://epherome.com/admin/${{ secrets.SITE_ADMIN_TOKEN }}/release/${{ github.event.inputs.tag }}
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Epherome ${{ github.event.inputs.tag }}
          body_path: docs/CHANGELOG.md
          prerelease: true
          files: |
            package/Epherome-${{ github.event.inputs.tag }}.exe
            package/Epherome-${{ github.event.inputs.tag }}.exe.hash
            package/Epherome-${{ github.event.inputs.tag }}.dmg
            package/Epherome-${{ github.event.inputs.tag }}.dmg.hash
            package/Epherome-${{ github.event.inputs.tag }}.tar.gz
            package/Epherome-${{ github.event.inputs.tag }}.tar.gz.hash
